
version: '3'
services:
  frontend:
    container_name: iemarjay.com_frontend
    image: iemarjay/website
    restart: always
    ports:
      - '${FRONTEND_PORT}:3000'
    environment:
      NEXT_PUBLIC_BACKEND_BASE_URL: ${NEXT_PUBLIC_BACKEND_BASE_URL}
      NODE_ENV: ${NODE_ENV}
    stdin_open: true
    tty: true
