services:
  frontend:
    container_name: iemarjay_frontend
    image: iemarjay/website
    restart: unless-stopped
    ports:
      - '${FRONTEND_PORT}:3000'
    environment:
      NEXT_PUBLIC_BACKEND_BASE_URL: ${NEXT_PUBLIC_BACKEND_BASE_URL}
      NODE_ENV: ${NODE_ENV}
    stdin_open: true
    tty: true
    networks:
      - server_nginx_network


  strapi:
    container_name: iemarjay_strapi
    image: strapi/strapi
    restart: unless-stopped
    tty: true
    stdin_open: true
    env_file:
      - .env
    ports:
      - "${STRAPI_PORT}:1337"
    volumes:
      - ./strapi:/srv/app
    networks:
      - server_nginx_network

networks:
  server_nginx_network:
    external: true
