
version: '3'
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '${FRONTEND_PORT}:3000'
    environment:
      NEXT_PUBLIC_BACKEND_BASE_URL: ${NEXT_PUBLIC_BACKEND_BASE_URL}
      NODE_ENV: ${NODE_ENV}
    stdin_open: true
    tty: true

volumes:
  strapi-data:
